kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    pod: free-websockets-web-container
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
