apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-local
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@site15.ru
    privateKeySecretRef:
      name: letsencrypt-local
    solvers:
      - http01:
          ingress:
            class: nginx
